version: '3.8'

services:
  app:
    build: .
    ports:
      - 3001:3001
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspaces:cached
    networks:
      - internal
    command: /bin/sh -c "while sleep 1000; do :; done"
    depends_on:
      - api-solid-pg

  api-solid-pg:
    image: bitnami/postgresql:latest
    container_name: api-solid-pg
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=apisolid
    ports:
      - 5433:5433

networks:
  internal:
